package com.yulink.texas.core.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class GameLogExample {
    protected String orderByClause;

    protected boolean distinct;

    protected List<Criteria> oredCriteria;

    protected Integer offset;

    protected Integer rows;

    public GameLogExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    public String getOrderByClause() {
        return orderByClause;
    }

    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    public boolean isDistinct() {
        return distinct;
    }

    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    public GameLogExample orderBy(String orderByClause) {
        this.setOrderByClause(orderByClause);
        return this;
    }

    public GameLogExample orderBy(String ... orderByClauses) {
        StringBuffer sb = new StringBuffer();
        for (int i = 0; i < orderByClauses.length; i++) {
            sb.append(orderByClauses[i]);
            if (i < orderByClauses.length - 1) {
                sb.append(" , ");
            }
        }
        this.setOrderByClause(sb.toString());
        return this;
    }

    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria(this);
        return criteria;
    }

    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
        rows = null;
        offset = null;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public Integer getOffset() {
        return this.offset;
    }

    public void setRows(Integer rows) {
        this.rows = rows;
    }

    public Integer getRows() {
        return this.rows;
    }

    public GameLogExample limit(Integer rows) {
        this.rows = rows;
        return this;
    }

    public GameLogExample limit(Integer offset, Integer rows) {
        this.offset = offset;
        this.rows = rows;
        return this;
    }

    public GameLogExample page(Integer page, Integer pageSize) {
        this.offset = page * pageSize;
        this.rows = pageSize;
        return this;
    }

    public static Criteria newAndCreateCriteria() {
        GameLogExample example = new GameLogExample();
        return example.createCriteria();
    }

    public GameLogExample when(boolean condition, IExampleWhen then) {
        if (condition) {
            then.example(this);
        }
        return this;
    }

    public GameLogExample when(boolean condition, IExampleWhen then, IExampleWhen otherwise) {
        if (condition) {
            then.example(this);
        } else {
            otherwise.example(this);
        }
        return this;
    }

    /**
            * This class was generated by MyBatis Generator.
            * This class corresponds to the database table t_game_log
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdEqualToColumn(GameLog.Column column) {
            addCriterion(new StringBuilder("id = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualToColumn(GameLog.Column column) {
            addCriterion(new StringBuilder("id <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanColumn(GameLog.Column column) {
            addCriterion(new StringBuilder("id > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualToColumn(GameLog.Column column) {
            addCriterion(new StringBuilder("id >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanColumn(GameLog.Column column) {
            addCriterion(new StringBuilder("id < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualToColumn(GameLog.Column column) {
            addCriterion(new StringBuilder("id <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andRoomtypeIsNull() {
            addCriterion("roomType is null");
            return (Criteria) this;
        }

        public Criteria andRoomtypeIsNotNull() {
            addCriterion("roomType is not null");
            return (Criteria) this;
        }

        public Criteria andRoomtypeEqualTo(String value) {
            addCriterion("roomType =", value, "roomtype");
            return (Criteria) this;
        }

        public Criteria andRoomtypeEqualToColumn(GameLog.Column column) {
            addCriterion(new StringBuilder("roomType = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRoomtypeNotEqualTo(String value) {
            addCriterion("roomType <>", value, "roomtype");
            return (Criteria) this;
        }

        public Criteria andRoomtypeNotEqualToColumn(GameLog.Column column) {
            addCriterion(new StringBuilder("roomType <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRoomtypeGreaterThan(String value) {
            addCriterion("roomType >", value, "roomtype");
            return (Criteria) this;
        }

        public Criteria andRoomtypeGreaterThanColumn(GameLog.Column column) {
            addCriterion(new StringBuilder("roomType > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRoomtypeGreaterThanOrEqualTo(String value) {
            addCriterion("roomType >=", value, "roomtype");
            return (Criteria) this;
        }

        public Criteria andRoomtypeGreaterThanOrEqualToColumn(GameLog.Column column) {
            addCriterion(new StringBuilder("roomType >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRoomtypeLessThan(String value) {
            addCriterion("roomType <", value, "roomtype");
            return (Criteria) this;
        }

        public Criteria andRoomtypeLessThanColumn(GameLog.Column column) {
            addCriterion(new StringBuilder("roomType < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRoomtypeLessThanOrEqualTo(String value) {
            addCriterion("roomType <=", value, "roomtype");
            return (Criteria) this;
        }

        public Criteria andRoomtypeLessThanOrEqualToColumn(GameLog.Column column) {
            addCriterion(new StringBuilder("roomType <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRoomtypeLike(String value) {
            addCriterion("roomType like", value, "roomtype");
            return (Criteria) this;
        }

        public Criteria andRoomtypeNotLike(String value) {
            addCriterion("roomType not like", value, "roomtype");
            return (Criteria) this;
        }

        public Criteria andRoomtypeIn(List<String> values) {
            addCriterion("roomType in", values, "roomtype");
            return (Criteria) this;
        }

        public Criteria andRoomtypeNotIn(List<String> values) {
            addCriterion("roomType not in", values, "roomtype");
            return (Criteria) this;
        }

        public Criteria andRoomtypeBetween(String value1, String value2) {
            addCriterion("roomType between", value1, value2, "roomtype");
            return (Criteria) this;
        }

        public Criteria andRoomtypeNotBetween(String value1, String value2) {
            addCriterion("roomType not between", value1, value2, "roomtype");
            return (Criteria) this;
        }

        public Criteria andRoomlevelIsNull() {
            addCriterion("roomLevel is null");
            return (Criteria) this;
        }

        public Criteria andRoomlevelIsNotNull() {
            addCriterion("roomLevel is not null");
            return (Criteria) this;
        }

        public Criteria andRoomlevelEqualTo(String value) {
            addCriterion("roomLevel =", value, "roomlevel");
            return (Criteria) this;
        }

        public Criteria andRoomlevelEqualToColumn(GameLog.Column column) {
            addCriterion(new StringBuilder("roomLevel = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRoomlevelNotEqualTo(String value) {
            addCriterion("roomLevel <>", value, "roomlevel");
            return (Criteria) this;
        }

        public Criteria andRoomlevelNotEqualToColumn(GameLog.Column column) {
            addCriterion(new StringBuilder("roomLevel <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRoomlevelGreaterThan(String value) {
            addCriterion("roomLevel >", value, "roomlevel");
            return (Criteria) this;
        }

        public Criteria andRoomlevelGreaterThanColumn(GameLog.Column column) {
            addCriterion(new StringBuilder("roomLevel > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRoomlevelGreaterThanOrEqualTo(String value) {
            addCriterion("roomLevel >=", value, "roomlevel");
            return (Criteria) this;
        }

        public Criteria andRoomlevelGreaterThanOrEqualToColumn(GameLog.Column column) {
            addCriterion(new StringBuilder("roomLevel >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRoomlevelLessThan(String value) {
            addCriterion("roomLevel <", value, "roomlevel");
            return (Criteria) this;
        }

        public Criteria andRoomlevelLessThanColumn(GameLog.Column column) {
            addCriterion(new StringBuilder("roomLevel < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRoomlevelLessThanOrEqualTo(String value) {
            addCriterion("roomLevel <=", value, "roomlevel");
            return (Criteria) this;
        }

        public Criteria andRoomlevelLessThanOrEqualToColumn(GameLog.Column column) {
            addCriterion(new StringBuilder("roomLevel <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRoomlevelLike(String value) {
            addCriterion("roomLevel like", value, "roomlevel");
            return (Criteria) this;
        }

        public Criteria andRoomlevelNotLike(String value) {
            addCriterion("roomLevel not like", value, "roomlevel");
            return (Criteria) this;
        }

        public Criteria andRoomlevelIn(List<String> values) {
            addCriterion("roomLevel in", values, "roomlevel");
            return (Criteria) this;
        }

        public Criteria andRoomlevelNotIn(List<String> values) {
            addCriterion("roomLevel not in", values, "roomlevel");
            return (Criteria) this;
        }

        public Criteria andRoomlevelBetween(String value1, String value2) {
            addCriterion("roomLevel between", value1, value2, "roomlevel");
            return (Criteria) this;
        }

        public Criteria andRoomlevelNotBetween(String value1, String value2) {
            addCriterion("roomLevel not between", value1, value2, "roomlevel");
            return (Criteria) this;
        }

        public Criteria andStarttimeIsNull() {
            addCriterion("startTime is null");
            return (Criteria) this;
        }

        public Criteria andStarttimeIsNotNull() {
            addCriterion("startTime is not null");
            return (Criteria) this;
        }

        public Criteria andStarttimeEqualTo(Date value) {
            addCriterion("startTime =", value, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeEqualToColumn(GameLog.Column column) {
            addCriterion(new StringBuilder("startTime = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStarttimeNotEqualTo(Date value) {
            addCriterion("startTime <>", value, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeNotEqualToColumn(GameLog.Column column) {
            addCriterion(new StringBuilder("startTime <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStarttimeGreaterThan(Date value) {
            addCriterion("startTime >", value, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeGreaterThanColumn(GameLog.Column column) {
            addCriterion(new StringBuilder("startTime > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStarttimeGreaterThanOrEqualTo(Date value) {
            addCriterion("startTime >=", value, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeGreaterThanOrEqualToColumn(GameLog.Column column) {
            addCriterion(new StringBuilder("startTime >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStarttimeLessThan(Date value) {
            addCriterion("startTime <", value, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeLessThanColumn(GameLog.Column column) {
            addCriterion(new StringBuilder("startTime < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStarttimeLessThanOrEqualTo(Date value) {
            addCriterion("startTime <=", value, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeLessThanOrEqualToColumn(GameLog.Column column) {
            addCriterion(new StringBuilder("startTime <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStarttimeIn(List<Date> values) {
            addCriterion("startTime in", values, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeNotIn(List<Date> values) {
            addCriterion("startTime not in", values, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeBetween(Date value1, Date value2) {
            addCriterion("startTime between", value1, value2, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeNotBetween(Date value1, Date value2) {
            addCriterion("startTime not between", value1, value2, "starttime");
            return (Criteria) this;
        }

        public Criteria andEndtimeIsNull() {
            addCriterion("endTime is null");
            return (Criteria) this;
        }

        public Criteria andEndtimeIsNotNull() {
            addCriterion("endTime is not null");
            return (Criteria) this;
        }

        public Criteria andEndtimeEqualTo(Date value) {
            addCriterion("endTime =", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeEqualToColumn(GameLog.Column column) {
            addCriterion(new StringBuilder("endTime = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andEndtimeNotEqualTo(Date value) {
            addCriterion("endTime <>", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeNotEqualToColumn(GameLog.Column column) {
            addCriterion(new StringBuilder("endTime <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andEndtimeGreaterThan(Date value) {
            addCriterion("endTime >", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeGreaterThanColumn(GameLog.Column column) {
            addCriterion(new StringBuilder("endTime > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andEndtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("endTime >=", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeGreaterThanOrEqualToColumn(GameLog.Column column) {
            addCriterion(new StringBuilder("endTime >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andEndtimeLessThan(Date value) {
            addCriterion("endTime <", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeLessThanColumn(GameLog.Column column) {
            addCriterion(new StringBuilder("endTime < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andEndtimeLessThanOrEqualTo(Date value) {
            addCriterion("endTime <=", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeLessThanOrEqualToColumn(GameLog.Column column) {
            addCriterion(new StringBuilder("endTime <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andEndtimeIn(List<Date> values) {
            addCriterion("endTime in", values, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeNotIn(List<Date> values) {
            addCriterion("endTime not in", values, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeBetween(Date value1, Date value2) {
            addCriterion("endTime between", value1, value2, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeNotBetween(Date value1, Date value2) {
            addCriterion("endTime not between", value1, value2, "endtime");
            return (Criteria) this;
        }

        public Criteria andCountbetpoolIsNull() {
            addCriterion("countBetpool is null");
            return (Criteria) this;
        }

        public Criteria andCountbetpoolIsNotNull() {
            addCriterion("countBetpool is not null");
            return (Criteria) this;
        }

        public Criteria andCountbetpoolEqualTo(Integer value) {
            addCriterion("countBetpool =", value, "countbetpool");
            return (Criteria) this;
        }

        public Criteria andCountbetpoolEqualToColumn(GameLog.Column column) {
            addCriterion(new StringBuilder("countBetpool = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCountbetpoolNotEqualTo(Integer value) {
            addCriterion("countBetpool <>", value, "countbetpool");
            return (Criteria) this;
        }

        public Criteria andCountbetpoolNotEqualToColumn(GameLog.Column column) {
            addCriterion(new StringBuilder("countBetpool <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCountbetpoolGreaterThan(Integer value) {
            addCriterion("countBetpool >", value, "countbetpool");
            return (Criteria) this;
        }

        public Criteria andCountbetpoolGreaterThanColumn(GameLog.Column column) {
            addCriterion(new StringBuilder("countBetpool > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCountbetpoolGreaterThanOrEqualTo(Integer value) {
            addCriterion("countBetpool >=", value, "countbetpool");
            return (Criteria) this;
        }

        public Criteria andCountbetpoolGreaterThanOrEqualToColumn(GameLog.Column column) {
            addCriterion(new StringBuilder("countBetpool >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCountbetpoolLessThan(Integer value) {
            addCriterion("countBetpool <", value, "countbetpool");
            return (Criteria) this;
        }

        public Criteria andCountbetpoolLessThanColumn(GameLog.Column column) {
            addCriterion(new StringBuilder("countBetpool < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCountbetpoolLessThanOrEqualTo(Integer value) {
            addCriterion("countBetpool <=", value, "countbetpool");
            return (Criteria) this;
        }

        public Criteria andCountbetpoolLessThanOrEqualToColumn(GameLog.Column column) {
            addCriterion(new StringBuilder("countBetpool <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCountbetpoolIn(List<Integer> values) {
            addCriterion("countBetpool in", values, "countbetpool");
            return (Criteria) this;
        }

        public Criteria andCountbetpoolNotIn(List<Integer> values) {
            addCriterion("countBetpool not in", values, "countbetpool");
            return (Criteria) this;
        }

        public Criteria andCountbetpoolBetween(Integer value1, Integer value2) {
            addCriterion("countBetpool between", value1, value2, "countbetpool");
            return (Criteria) this;
        }

        public Criteria andCountbetpoolNotBetween(Integer value1, Integer value2) {
            addCriterion("countBetpool not between", value1, value2, "countbetpool");
            return (Criteria) this;
        }

        public Criteria andCutIsNull() {
            addCriterion("cut is null");
            return (Criteria) this;
        }

        public Criteria andCutIsNotNull() {
            addCriterion("cut is not null");
            return (Criteria) this;
        }

        public Criteria andCutEqualTo(Integer value) {
            addCriterion("cut =", value, "cut");
            return (Criteria) this;
        }

        public Criteria andCutEqualToColumn(GameLog.Column column) {
            addCriterion(new StringBuilder("cut = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCutNotEqualTo(Integer value) {
            addCriterion("cut <>", value, "cut");
            return (Criteria) this;
        }

        public Criteria andCutNotEqualToColumn(GameLog.Column column) {
            addCriterion(new StringBuilder("cut <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCutGreaterThan(Integer value) {
            addCriterion("cut >", value, "cut");
            return (Criteria) this;
        }

        public Criteria andCutGreaterThanColumn(GameLog.Column column) {
            addCriterion(new StringBuilder("cut > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCutGreaterThanOrEqualTo(Integer value) {
            addCriterion("cut >=", value, "cut");
            return (Criteria) this;
        }

        public Criteria andCutGreaterThanOrEqualToColumn(GameLog.Column column) {
            addCriterion(new StringBuilder("cut >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCutLessThan(Integer value) {
            addCriterion("cut <", value, "cut");
            return (Criteria) this;
        }

        public Criteria andCutLessThanColumn(GameLog.Column column) {
            addCriterion(new StringBuilder("cut < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCutLessThanOrEqualTo(Integer value) {
            addCriterion("cut <=", value, "cut");
            return (Criteria) this;
        }

        public Criteria andCutLessThanOrEqualToColumn(GameLog.Column column) {
            addCriterion(new StringBuilder("cut <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCutIn(List<Integer> values) {
            addCriterion("cut in", values, "cut");
            return (Criteria) this;
        }

        public Criteria andCutNotIn(List<Integer> values) {
            addCriterion("cut not in", values, "cut");
            return (Criteria) this;
        }

        public Criteria andCutBetween(Integer value1, Integer value2) {
            addCriterion("cut between", value1, value2, "cut");
            return (Criteria) this;
        }

        public Criteria andCutNotBetween(Integer value1, Integer value2) {
            addCriterion("cut not between", value1, value2, "cut");
            return (Criteria) this;
        }
    }

    /**
            * This class was generated by MyBatis Generator.
            * This class corresponds to the database table t_game_log
            *
            * @mbg.generated do_not_delete_during_merge
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    public static class Criteria extends GeneratedCriteria {
        private GameLogExample example;

        protected Criteria(GameLogExample example) {
            super();
            this.example = example;
        }

        public GameLogExample example() {
            return this.example;
        }

        @Deprecated
        public Criteria andIf(boolean ifAdd, ICriteriaAdd add) {
            if (ifAdd) {
                add.add(this);
            }
            return this;
        }

        public Criteria when(boolean condition, ICriteriaWhen then) {
            if (condition) {
                then.criteria(this);
            }
            return this;
        }

        public Criteria when(boolean condition, ICriteriaWhen then, ICriteriaWhen otherwise) {
            if (condition) {
                then.criteria(this);
            } else {
                otherwise.criteria(this);
            }
            return this;
        }

        @Deprecated
        public interface ICriteriaAdd {
            Criteria add(Criteria add);
        }
    }

    /**
            * This class was generated by MyBatis Generator.
            * This class corresponds to the database table t_game_log
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    public interface ICriteriaWhen {
        void criteria(Criteria criteria);
    }

    public interface IExampleWhen {
        void example(com.yulink.texas.core.domain.GameLogExample example);
    }
}