package com.yulink.texas.core.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SkillCombinationExample {
    protected String orderByClause;

    protected boolean distinct;

    protected List<Criteria> oredCriteria;

    protected Integer offset;

    protected Integer rows;

    public SkillCombinationExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    public String getOrderByClause() {
        return orderByClause;
    }

    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    public boolean isDistinct() {
        return distinct;
    }

    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    public SkillCombinationExample orderBy(String orderByClause) {
        this.setOrderByClause(orderByClause);
        return this;
    }

    public SkillCombinationExample orderBy(String ... orderByClauses) {
        StringBuffer sb = new StringBuffer();
        for (int i = 0; i < orderByClauses.length; i++) {
            sb.append(orderByClauses[i]);
            if (i < orderByClauses.length - 1) {
                sb.append(" , ");
            }
        }
        this.setOrderByClause(sb.toString());
        return this;
    }

    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria(this);
        return criteria;
    }

    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
        rows = null;
        offset = null;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public Integer getOffset() {
        return this.offset;
    }

    public void setRows(Integer rows) {
        this.rows = rows;
    }

    public Integer getRows() {
        return this.rows;
    }

    public SkillCombinationExample limit(Integer rows) {
        this.rows = rows;
        return this;
    }

    public SkillCombinationExample limit(Integer offset, Integer rows) {
        this.offset = offset;
        this.rows = rows;
        return this;
    }

    public SkillCombinationExample page(Integer page, Integer pageSize) {
        this.offset = page * pageSize;
        this.rows = pageSize;
        return this;
    }

    public static Criteria newAndCreateCriteria() {
        SkillCombinationExample example = new SkillCombinationExample();
        return example.createCriteria();
    }

    public SkillCombinationExample when(boolean condition, IExampleWhen then) {
        if (condition) {
            then.example(this);
        }
        return this;
    }

    public SkillCombinationExample when(boolean condition, IExampleWhen then, IExampleWhen otherwise) {
        if (condition) {
            then.example(this);
        } else {
            otherwise.example(this);
        }
        return this;
    }

    /**
            * This class was generated by MyBatis Generator.
            * This class corresponds to the database table t_skill_combination
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdEqualToColumn(SkillCombination.Column column) {
            addCriterion(new StringBuilder("id = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualToColumn(SkillCombination.Column column) {
            addCriterion(new StringBuilder("id <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanColumn(SkillCombination.Column column) {
            addCriterion(new StringBuilder("id > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualToColumn(SkillCombination.Column column) {
            addCriterion(new StringBuilder("id >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanColumn(SkillCombination.Column column) {
            addCriterion(new StringBuilder("id < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualToColumn(SkillCombination.Column column) {
            addCriterion(new StringBuilder("id <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSkillCombinationNoIsNull() {
            addCriterion("skill_combination_no is null");
            return (Criteria) this;
        }

        public Criteria andSkillCombinationNoIsNotNull() {
            addCriterion("skill_combination_no is not null");
            return (Criteria) this;
        }

        public Criteria andSkillCombinationNoEqualTo(String value) {
            addCriterion("skill_combination_no =", value, "skillCombinationNo");
            return (Criteria) this;
        }

        public Criteria andSkillCombinationNoEqualToColumn(SkillCombination.Column column) {
            addCriterion(new StringBuilder("skill_combination_no = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSkillCombinationNoNotEqualTo(String value) {
            addCriterion("skill_combination_no <>", value, "skillCombinationNo");
            return (Criteria) this;
        }

        public Criteria andSkillCombinationNoNotEqualToColumn(SkillCombination.Column column) {
            addCriterion(new StringBuilder("skill_combination_no <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSkillCombinationNoGreaterThan(String value) {
            addCriterion("skill_combination_no >", value, "skillCombinationNo");
            return (Criteria) this;
        }

        public Criteria andSkillCombinationNoGreaterThanColumn(SkillCombination.Column column) {
            addCriterion(new StringBuilder("skill_combination_no > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSkillCombinationNoGreaterThanOrEqualTo(String value) {
            addCriterion("skill_combination_no >=", value, "skillCombinationNo");
            return (Criteria) this;
        }

        public Criteria andSkillCombinationNoGreaterThanOrEqualToColumn(SkillCombination.Column column) {
            addCriterion(new StringBuilder("skill_combination_no >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSkillCombinationNoLessThan(String value) {
            addCriterion("skill_combination_no <", value, "skillCombinationNo");
            return (Criteria) this;
        }

        public Criteria andSkillCombinationNoLessThanColumn(SkillCombination.Column column) {
            addCriterion(new StringBuilder("skill_combination_no < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSkillCombinationNoLessThanOrEqualTo(String value) {
            addCriterion("skill_combination_no <=", value, "skillCombinationNo");
            return (Criteria) this;
        }

        public Criteria andSkillCombinationNoLessThanOrEqualToColumn(SkillCombination.Column column) {
            addCriterion(new StringBuilder("skill_combination_no <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSkillCombinationNoLike(String value) {
            addCriterion("skill_combination_no like", value, "skillCombinationNo");
            return (Criteria) this;
        }

        public Criteria andSkillCombinationNoNotLike(String value) {
            addCriterion("skill_combination_no not like", value, "skillCombinationNo");
            return (Criteria) this;
        }

        public Criteria andSkillCombinationNoIn(List<String> values) {
            addCriterion("skill_combination_no in", values, "skillCombinationNo");
            return (Criteria) this;
        }

        public Criteria andSkillCombinationNoNotIn(List<String> values) {
            addCriterion("skill_combination_no not in", values, "skillCombinationNo");
            return (Criteria) this;
        }

        public Criteria andSkillCombinationNoBetween(String value1, String value2) {
            addCriterion("skill_combination_no between", value1, value2, "skillCombinationNo");
            return (Criteria) this;
        }

        public Criteria andSkillCombinationNoNotBetween(String value1, String value2) {
            addCriterion("skill_combination_no not between", value1, value2, "skillCombinationNo");
            return (Criteria) this;
        }

        public Criteria andSkillCombinationNameIsNull() {
            addCriterion("skill_combination_name is null");
            return (Criteria) this;
        }

        public Criteria andSkillCombinationNameIsNotNull() {
            addCriterion("skill_combination_name is not null");
            return (Criteria) this;
        }

        public Criteria andSkillCombinationNameEqualTo(String value) {
            addCriterion("skill_combination_name =", value, "skillCombinationName");
            return (Criteria) this;
        }

        public Criteria andSkillCombinationNameEqualToColumn(SkillCombination.Column column) {
            addCriterion(new StringBuilder("skill_combination_name = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSkillCombinationNameNotEqualTo(String value) {
            addCriterion("skill_combination_name <>", value, "skillCombinationName");
            return (Criteria) this;
        }

        public Criteria andSkillCombinationNameNotEqualToColumn(SkillCombination.Column column) {
            addCriterion(new StringBuilder("skill_combination_name <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSkillCombinationNameGreaterThan(String value) {
            addCriterion("skill_combination_name >", value, "skillCombinationName");
            return (Criteria) this;
        }

        public Criteria andSkillCombinationNameGreaterThanColumn(SkillCombination.Column column) {
            addCriterion(new StringBuilder("skill_combination_name > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSkillCombinationNameGreaterThanOrEqualTo(String value) {
            addCriterion("skill_combination_name >=", value, "skillCombinationName");
            return (Criteria) this;
        }

        public Criteria andSkillCombinationNameGreaterThanOrEqualToColumn(SkillCombination.Column column) {
            addCriterion(new StringBuilder("skill_combination_name >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSkillCombinationNameLessThan(String value) {
            addCriterion("skill_combination_name <", value, "skillCombinationName");
            return (Criteria) this;
        }

        public Criteria andSkillCombinationNameLessThanColumn(SkillCombination.Column column) {
            addCriterion(new StringBuilder("skill_combination_name < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSkillCombinationNameLessThanOrEqualTo(String value) {
            addCriterion("skill_combination_name <=", value, "skillCombinationName");
            return (Criteria) this;
        }

        public Criteria andSkillCombinationNameLessThanOrEqualToColumn(SkillCombination.Column column) {
            addCriterion(new StringBuilder("skill_combination_name <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSkillCombinationNameLike(String value) {
            addCriterion("skill_combination_name like", value, "skillCombinationName");
            return (Criteria) this;
        }

        public Criteria andSkillCombinationNameNotLike(String value) {
            addCriterion("skill_combination_name not like", value, "skillCombinationName");
            return (Criteria) this;
        }

        public Criteria andSkillCombinationNameIn(List<String> values) {
            addCriterion("skill_combination_name in", values, "skillCombinationName");
            return (Criteria) this;
        }

        public Criteria andSkillCombinationNameNotIn(List<String> values) {
            addCriterion("skill_combination_name not in", values, "skillCombinationName");
            return (Criteria) this;
        }

        public Criteria andSkillCombinationNameBetween(String value1, String value2) {
            addCriterion("skill_combination_name between", value1, value2, "skillCombinationName");
            return (Criteria) this;
        }

        public Criteria andSkillCombinationNameNotBetween(String value1, String value2) {
            addCriterion("skill_combination_name not between", value1, value2, "skillCombinationName");
            return (Criteria) this;
        }

        public Criteria andSkillCardNoIsNull() {
            addCriterion("skill_card_no is null");
            return (Criteria) this;
        }

        public Criteria andSkillCardNoIsNotNull() {
            addCriterion("skill_card_no is not null");
            return (Criteria) this;
        }

        public Criteria andSkillCardNoEqualTo(String value) {
            addCriterion("skill_card_no =", value, "skillCardNo");
            return (Criteria) this;
        }

        public Criteria andSkillCardNoEqualToColumn(SkillCombination.Column column) {
            addCriterion(new StringBuilder("skill_card_no = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSkillCardNoNotEqualTo(String value) {
            addCriterion("skill_card_no <>", value, "skillCardNo");
            return (Criteria) this;
        }

        public Criteria andSkillCardNoNotEqualToColumn(SkillCombination.Column column) {
            addCriterion(new StringBuilder("skill_card_no <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSkillCardNoGreaterThan(String value) {
            addCriterion("skill_card_no >", value, "skillCardNo");
            return (Criteria) this;
        }

        public Criteria andSkillCardNoGreaterThanColumn(SkillCombination.Column column) {
            addCriterion(new StringBuilder("skill_card_no > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSkillCardNoGreaterThanOrEqualTo(String value) {
            addCriterion("skill_card_no >=", value, "skillCardNo");
            return (Criteria) this;
        }

        public Criteria andSkillCardNoGreaterThanOrEqualToColumn(SkillCombination.Column column) {
            addCriterion(new StringBuilder("skill_card_no >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSkillCardNoLessThan(String value) {
            addCriterion("skill_card_no <", value, "skillCardNo");
            return (Criteria) this;
        }

        public Criteria andSkillCardNoLessThanColumn(SkillCombination.Column column) {
            addCriterion(new StringBuilder("skill_card_no < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSkillCardNoLessThanOrEqualTo(String value) {
            addCriterion("skill_card_no <=", value, "skillCardNo");
            return (Criteria) this;
        }

        public Criteria andSkillCardNoLessThanOrEqualToColumn(SkillCombination.Column column) {
            addCriterion(new StringBuilder("skill_card_no <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSkillCardNoLike(String value) {
            addCriterion("skill_card_no like", value, "skillCardNo");
            return (Criteria) this;
        }

        public Criteria andSkillCardNoNotLike(String value) {
            addCriterion("skill_card_no not like", value, "skillCardNo");
            return (Criteria) this;
        }

        public Criteria andSkillCardNoIn(List<String> values) {
            addCriterion("skill_card_no in", values, "skillCardNo");
            return (Criteria) this;
        }

        public Criteria andSkillCardNoNotIn(List<String> values) {
            addCriterion("skill_card_no not in", values, "skillCardNo");
            return (Criteria) this;
        }

        public Criteria andSkillCardNoBetween(String value1, String value2) {
            addCriterion("skill_card_no between", value1, value2, "skillCardNo");
            return (Criteria) this;
        }

        public Criteria andSkillCardNoNotBetween(String value1, String value2) {
            addCriterion("skill_card_no not between", value1, value2, "skillCardNo");
            return (Criteria) this;
        }

        public Criteria andPlayerOidIsNull() {
            addCriterion("player_oid is null");
            return (Criteria) this;
        }

        public Criteria andPlayerOidIsNotNull() {
            addCriterion("player_oid is not null");
            return (Criteria) this;
        }

        public Criteria andPlayerOidEqualTo(Integer value) {
            addCriterion("player_oid =", value, "playerOid");
            return (Criteria) this;
        }

        public Criteria andPlayerOidEqualToColumn(SkillCombination.Column column) {
            addCriterion(new StringBuilder("player_oid = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andPlayerOidNotEqualTo(Integer value) {
            addCriterion("player_oid <>", value, "playerOid");
            return (Criteria) this;
        }

        public Criteria andPlayerOidNotEqualToColumn(SkillCombination.Column column) {
            addCriterion(new StringBuilder("player_oid <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andPlayerOidGreaterThan(Integer value) {
            addCriterion("player_oid >", value, "playerOid");
            return (Criteria) this;
        }

        public Criteria andPlayerOidGreaterThanColumn(SkillCombination.Column column) {
            addCriterion(new StringBuilder("player_oid > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andPlayerOidGreaterThanOrEqualTo(Integer value) {
            addCriterion("player_oid >=", value, "playerOid");
            return (Criteria) this;
        }

        public Criteria andPlayerOidGreaterThanOrEqualToColumn(SkillCombination.Column column) {
            addCriterion(new StringBuilder("player_oid >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andPlayerOidLessThan(Integer value) {
            addCriterion("player_oid <", value, "playerOid");
            return (Criteria) this;
        }

        public Criteria andPlayerOidLessThanColumn(SkillCombination.Column column) {
            addCriterion(new StringBuilder("player_oid < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andPlayerOidLessThanOrEqualTo(Integer value) {
            addCriterion("player_oid <=", value, "playerOid");
            return (Criteria) this;
        }

        public Criteria andPlayerOidLessThanOrEqualToColumn(SkillCombination.Column column) {
            addCriterion(new StringBuilder("player_oid <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andPlayerOidIn(List<Integer> values) {
            addCriterion("player_oid in", values, "playerOid");
            return (Criteria) this;
        }

        public Criteria andPlayerOidNotIn(List<Integer> values) {
            addCriterion("player_oid not in", values, "playerOid");
            return (Criteria) this;
        }

        public Criteria andPlayerOidBetween(Integer value1, Integer value2) {
            addCriterion("player_oid between", value1, value2, "playerOid");
            return (Criteria) this;
        }

        public Criteria andPlayerOidNotBetween(Integer value1, Integer value2) {
            addCriterion("player_oid not between", value1, value2, "playerOid");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeEqualToColumn(SkillCombination.Column column) {
            addCriterion(new StringBuilder("type = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualToColumn(SkillCombination.Column column) {
            addCriterion(new StringBuilder("type <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanColumn(SkillCombination.Column column) {
            addCriterion(new StringBuilder("type > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualToColumn(SkillCombination.Column column) {
            addCriterion(new StringBuilder("type >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanColumn(SkillCombination.Column column) {
            addCriterion(new StringBuilder("type < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualToColumn(SkillCombination.Column column) {
            addCriterion(new StringBuilder("type <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusEqualToColumn(SkillCombination.Column column) {
            addCriterion(new StringBuilder("status = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualToColumn(SkillCombination.Column column) {
            addCriterion(new StringBuilder("status <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanColumn(SkillCombination.Column column) {
            addCriterion(new StringBuilder("status > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualToColumn(SkillCombination.Column column) {
            addCriterion(new StringBuilder("status >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanColumn(SkillCombination.Column column) {
            addCriterion(new StringBuilder("status < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualToColumn(SkillCombination.Column column) {
            addCriterion(new StringBuilder("status <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualToColumn(SkillCombination.Column column) {
            addCriterion(new StringBuilder("remark = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualToColumn(SkillCombination.Column column) {
            addCriterion(new StringBuilder("remark <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanColumn(SkillCombination.Column column) {
            addCriterion(new StringBuilder("remark > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualToColumn(SkillCombination.Column column) {
            addCriterion(new StringBuilder("remark >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanColumn(SkillCombination.Column column) {
            addCriterion(new StringBuilder("remark < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualToColumn(SkillCombination.Column column) {
            addCriterion(new StringBuilder("remark <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualToColumn(SkillCombination.Column column) {
            addCriterion(new StringBuilder("create_time = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualToColumn(SkillCombination.Column column) {
            addCriterion(new StringBuilder("create_time <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanColumn(SkillCombination.Column column) {
            addCriterion(new StringBuilder("create_time > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualToColumn(SkillCombination.Column column) {
            addCriterion(new StringBuilder("create_time >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanColumn(SkillCombination.Column column) {
            addCriterion(new StringBuilder("create_time < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualToColumn(SkillCombination.Column column) {
            addCriterion(new StringBuilder("create_time <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }
    }

    /**
            * This class was generated by MyBatis Generator.
            * This class corresponds to the database table t_skill_combination
            *
            * @mbg.generated do_not_delete_during_merge
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    public static class Criteria extends GeneratedCriteria {
        private SkillCombinationExample example;

        protected Criteria(SkillCombinationExample example) {
            super();
            this.example = example;
        }

        public SkillCombinationExample example() {
            return this.example;
        }

        @Deprecated
        public Criteria andIf(boolean ifAdd, ICriteriaAdd add) {
            if (ifAdd) {
                add.add(this);
            }
            return this;
        }

        public Criteria when(boolean condition, ICriteriaWhen then) {
            if (condition) {
                then.criteria(this);
            }
            return this;
        }

        public Criteria when(boolean condition, ICriteriaWhen then, ICriteriaWhen otherwise) {
            if (condition) {
                then.criteria(this);
            } else {
                otherwise.criteria(this);
            }
            return this;
        }

        @Deprecated
        public interface ICriteriaAdd {
            Criteria add(Criteria add);
        }
    }

    /**
            * This class was generated by MyBatis Generator.
            * This class corresponds to the database table t_skill_combination
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    public interface ICriteriaWhen {
        void criteria(Criteria criteria);
    }

    public interface IExampleWhen {
        void example(com.yulink.texas.core.domain.SkillCombinationExample example);
    }
}