package com.yulink.texas.core.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SkillCardExample {
    protected String orderByClause;

    protected boolean distinct;

    protected List<Criteria> oredCriteria;

    protected Integer offset;

    protected Integer rows;

    public SkillCardExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    public String getOrderByClause() {
        return orderByClause;
    }

    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    public boolean isDistinct() {
        return distinct;
    }

    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    public SkillCardExample orderBy(String orderByClause) {
        this.setOrderByClause(orderByClause);
        return this;
    }

    public SkillCardExample orderBy(String ... orderByClauses) {
        StringBuffer sb = new StringBuffer();
        for (int i = 0; i < orderByClauses.length; i++) {
            sb.append(orderByClauses[i]);
            if (i < orderByClauses.length - 1) {
                sb.append(" , ");
            }
        }
        this.setOrderByClause(sb.toString());
        return this;
    }

    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria(this);
        return criteria;
    }

    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
        rows = null;
        offset = null;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public Integer getOffset() {
        return this.offset;
    }

    public void setRows(Integer rows) {
        this.rows = rows;
    }

    public Integer getRows() {
        return this.rows;
    }

    public SkillCardExample limit(Integer rows) {
        this.rows = rows;
        return this;
    }

    public SkillCardExample limit(Integer offset, Integer rows) {
        this.offset = offset;
        this.rows = rows;
        return this;
    }

    public SkillCardExample page(Integer page, Integer pageSize) {
        this.offset = page * pageSize;
        this.rows = pageSize;
        return this;
    }

    public static Criteria newAndCreateCriteria() {
        SkillCardExample example = new SkillCardExample();
        return example.createCriteria();
    }

    public SkillCardExample when(boolean condition, IExampleWhen then) {
        if (condition) {
            then.example(this);
        }
        return this;
    }

    public SkillCardExample when(boolean condition, IExampleWhen then, IExampleWhen otherwise) {
        if (condition) {
            then.example(this);
        } else {
            otherwise.example(this);
        }
        return this;
    }

    /**
            * This class was generated by MyBatis Generator.
            * This class corresponds to the database table t_skill_card
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdEqualToColumn(SkillCard.Column column) {
            addCriterion(new StringBuilder("id = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualToColumn(SkillCard.Column column) {
            addCriterion(new StringBuilder("id <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanColumn(SkillCard.Column column) {
            addCriterion(new StringBuilder("id > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualToColumn(SkillCard.Column column) {
            addCriterion(new StringBuilder("id >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanColumn(SkillCard.Column column) {
            addCriterion(new StringBuilder("id < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualToColumn(SkillCard.Column column) {
            addCriterion(new StringBuilder("id <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSkillCardNoIsNull() {
            addCriterion("skill_card_no is null");
            return (Criteria) this;
        }

        public Criteria andSkillCardNoIsNotNull() {
            addCriterion("skill_card_no is not null");
            return (Criteria) this;
        }

        public Criteria andSkillCardNoEqualTo(String value) {
            addCriterion("skill_card_no =", value, "skillCardNo");
            return (Criteria) this;
        }

        public Criteria andSkillCardNoEqualToColumn(SkillCard.Column column) {
            addCriterion(new StringBuilder("skill_card_no = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSkillCardNoNotEqualTo(String value) {
            addCriterion("skill_card_no <>", value, "skillCardNo");
            return (Criteria) this;
        }

        public Criteria andSkillCardNoNotEqualToColumn(SkillCard.Column column) {
            addCriterion(new StringBuilder("skill_card_no <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSkillCardNoGreaterThan(String value) {
            addCriterion("skill_card_no >", value, "skillCardNo");
            return (Criteria) this;
        }

        public Criteria andSkillCardNoGreaterThanColumn(SkillCard.Column column) {
            addCriterion(new StringBuilder("skill_card_no > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSkillCardNoGreaterThanOrEqualTo(String value) {
            addCriterion("skill_card_no >=", value, "skillCardNo");
            return (Criteria) this;
        }

        public Criteria andSkillCardNoGreaterThanOrEqualToColumn(SkillCard.Column column) {
            addCriterion(new StringBuilder("skill_card_no >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSkillCardNoLessThan(String value) {
            addCriterion("skill_card_no <", value, "skillCardNo");
            return (Criteria) this;
        }

        public Criteria andSkillCardNoLessThanColumn(SkillCard.Column column) {
            addCriterion(new StringBuilder("skill_card_no < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSkillCardNoLessThanOrEqualTo(String value) {
            addCriterion("skill_card_no <=", value, "skillCardNo");
            return (Criteria) this;
        }

        public Criteria andSkillCardNoLessThanOrEqualToColumn(SkillCard.Column column) {
            addCriterion(new StringBuilder("skill_card_no <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSkillCardNoLike(String value) {
            addCriterion("skill_card_no like", value, "skillCardNo");
            return (Criteria) this;
        }

        public Criteria andSkillCardNoNotLike(String value) {
            addCriterion("skill_card_no not like", value, "skillCardNo");
            return (Criteria) this;
        }

        public Criteria andSkillCardNoIn(List<String> values) {
            addCriterion("skill_card_no in", values, "skillCardNo");
            return (Criteria) this;
        }

        public Criteria andSkillCardNoNotIn(List<String> values) {
            addCriterion("skill_card_no not in", values, "skillCardNo");
            return (Criteria) this;
        }

        public Criteria andSkillCardNoBetween(String value1, String value2) {
            addCriterion("skill_card_no between", value1, value2, "skillCardNo");
            return (Criteria) this;
        }

        public Criteria andSkillCardNoNotBetween(String value1, String value2) {
            addCriterion("skill_card_no not between", value1, value2, "skillCardNo");
            return (Criteria) this;
        }

        public Criteria andSkillDictionaryNoIsNull() {
            addCriterion("skill_dictionary_no is null");
            return (Criteria) this;
        }

        public Criteria andSkillDictionaryNoIsNotNull() {
            addCriterion("skill_dictionary_no is not null");
            return (Criteria) this;
        }

        public Criteria andSkillDictionaryNoEqualTo(String value) {
            addCriterion("skill_dictionary_no =", value, "skillDictionaryNo");
            return (Criteria) this;
        }

        public Criteria andSkillDictionaryNoEqualToColumn(SkillCard.Column column) {
            addCriterion(new StringBuilder("skill_dictionary_no = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSkillDictionaryNoNotEqualTo(String value) {
            addCriterion("skill_dictionary_no <>", value, "skillDictionaryNo");
            return (Criteria) this;
        }

        public Criteria andSkillDictionaryNoNotEqualToColumn(SkillCard.Column column) {
            addCriterion(new StringBuilder("skill_dictionary_no <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSkillDictionaryNoGreaterThan(String value) {
            addCriterion("skill_dictionary_no >", value, "skillDictionaryNo");
            return (Criteria) this;
        }

        public Criteria andSkillDictionaryNoGreaterThanColumn(SkillCard.Column column) {
            addCriterion(new StringBuilder("skill_dictionary_no > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSkillDictionaryNoGreaterThanOrEqualTo(String value) {
            addCriterion("skill_dictionary_no >=", value, "skillDictionaryNo");
            return (Criteria) this;
        }

        public Criteria andSkillDictionaryNoGreaterThanOrEqualToColumn(SkillCard.Column column) {
            addCriterion(new StringBuilder("skill_dictionary_no >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSkillDictionaryNoLessThan(String value) {
            addCriterion("skill_dictionary_no <", value, "skillDictionaryNo");
            return (Criteria) this;
        }

        public Criteria andSkillDictionaryNoLessThanColumn(SkillCard.Column column) {
            addCriterion(new StringBuilder("skill_dictionary_no < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSkillDictionaryNoLessThanOrEqualTo(String value) {
            addCriterion("skill_dictionary_no <=", value, "skillDictionaryNo");
            return (Criteria) this;
        }

        public Criteria andSkillDictionaryNoLessThanOrEqualToColumn(SkillCard.Column column) {
            addCriterion(new StringBuilder("skill_dictionary_no <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSkillDictionaryNoLike(String value) {
            addCriterion("skill_dictionary_no like", value, "skillDictionaryNo");
            return (Criteria) this;
        }

        public Criteria andSkillDictionaryNoNotLike(String value) {
            addCriterion("skill_dictionary_no not like", value, "skillDictionaryNo");
            return (Criteria) this;
        }

        public Criteria andSkillDictionaryNoIn(List<String> values) {
            addCriterion("skill_dictionary_no in", values, "skillDictionaryNo");
            return (Criteria) this;
        }

        public Criteria andSkillDictionaryNoNotIn(List<String> values) {
            addCriterion("skill_dictionary_no not in", values, "skillDictionaryNo");
            return (Criteria) this;
        }

        public Criteria andSkillDictionaryNoBetween(String value1, String value2) {
            addCriterion("skill_dictionary_no between", value1, value2, "skillDictionaryNo");
            return (Criteria) this;
        }

        public Criteria andSkillDictionaryNoNotBetween(String value1, String value2) {
            addCriterion("skill_dictionary_no not between", value1, value2, "skillDictionaryNo");
            return (Criteria) this;
        }

        public Criteria andTokenidIsNull() {
            addCriterion("tokenId is null");
            return (Criteria) this;
        }

        public Criteria andTokenidIsNotNull() {
            addCriterion("tokenId is not null");
            return (Criteria) this;
        }

        public Criteria andTokenidEqualTo(String value) {
            addCriterion("tokenId =", value, "tokenid");
            return (Criteria) this;
        }

        public Criteria andTokenidEqualToColumn(SkillCard.Column column) {
            addCriterion(new StringBuilder("tokenId = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTokenidNotEqualTo(String value) {
            addCriterion("tokenId <>", value, "tokenid");
            return (Criteria) this;
        }

        public Criteria andTokenidNotEqualToColumn(SkillCard.Column column) {
            addCriterion(new StringBuilder("tokenId <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTokenidGreaterThan(String value) {
            addCriterion("tokenId >", value, "tokenid");
            return (Criteria) this;
        }

        public Criteria andTokenidGreaterThanColumn(SkillCard.Column column) {
            addCriterion(new StringBuilder("tokenId > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTokenidGreaterThanOrEqualTo(String value) {
            addCriterion("tokenId >=", value, "tokenid");
            return (Criteria) this;
        }

        public Criteria andTokenidGreaterThanOrEqualToColumn(SkillCard.Column column) {
            addCriterion(new StringBuilder("tokenId >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTokenidLessThan(String value) {
            addCriterion("tokenId <", value, "tokenid");
            return (Criteria) this;
        }

        public Criteria andTokenidLessThanColumn(SkillCard.Column column) {
            addCriterion(new StringBuilder("tokenId < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTokenidLessThanOrEqualTo(String value) {
            addCriterion("tokenId <=", value, "tokenid");
            return (Criteria) this;
        }

        public Criteria andTokenidLessThanOrEqualToColumn(SkillCard.Column column) {
            addCriterion(new StringBuilder("tokenId <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTokenidLike(String value) {
            addCriterion("tokenId like", value, "tokenid");
            return (Criteria) this;
        }

        public Criteria andTokenidNotLike(String value) {
            addCriterion("tokenId not like", value, "tokenid");
            return (Criteria) this;
        }

        public Criteria andTokenidIn(List<String> values) {
            addCriterion("tokenId in", values, "tokenid");
            return (Criteria) this;
        }

        public Criteria andTokenidNotIn(List<String> values) {
            addCriterion("tokenId not in", values, "tokenid");
            return (Criteria) this;
        }

        public Criteria andTokenidBetween(String value1, String value2) {
            addCriterion("tokenId between", value1, value2, "tokenid");
            return (Criteria) this;
        }

        public Criteria andTokenidNotBetween(String value1, String value2) {
            addCriterion("tokenId not between", value1, value2, "tokenid");
            return (Criteria) this;
        }

        public Criteria andPlayerOidIsNull() {
            addCriterion("player_oid is null");
            return (Criteria) this;
        }

        public Criteria andPlayerOidIsNotNull() {
            addCriterion("player_oid is not null");
            return (Criteria) this;
        }

        public Criteria andPlayerOidEqualTo(Integer value) {
            addCriterion("player_oid =", value, "playerOid");
            return (Criteria) this;
        }

        public Criteria andPlayerOidEqualToColumn(SkillCard.Column column) {
            addCriterion(new StringBuilder("player_oid = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andPlayerOidNotEqualTo(Integer value) {
            addCriterion("player_oid <>", value, "playerOid");
            return (Criteria) this;
        }

        public Criteria andPlayerOidNotEqualToColumn(SkillCard.Column column) {
            addCriterion(new StringBuilder("player_oid <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andPlayerOidGreaterThan(Integer value) {
            addCriterion("player_oid >", value, "playerOid");
            return (Criteria) this;
        }

        public Criteria andPlayerOidGreaterThanColumn(SkillCard.Column column) {
            addCriterion(new StringBuilder("player_oid > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andPlayerOidGreaterThanOrEqualTo(Integer value) {
            addCriterion("player_oid >=", value, "playerOid");
            return (Criteria) this;
        }

        public Criteria andPlayerOidGreaterThanOrEqualToColumn(SkillCard.Column column) {
            addCriterion(new StringBuilder("player_oid >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andPlayerOidLessThan(Integer value) {
            addCriterion("player_oid <", value, "playerOid");
            return (Criteria) this;
        }

        public Criteria andPlayerOidLessThanColumn(SkillCard.Column column) {
            addCriterion(new StringBuilder("player_oid < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andPlayerOidLessThanOrEqualTo(Integer value) {
            addCriterion("player_oid <=", value, "playerOid");
            return (Criteria) this;
        }

        public Criteria andPlayerOidLessThanOrEqualToColumn(SkillCard.Column column) {
            addCriterion(new StringBuilder("player_oid <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andPlayerOidIn(List<Integer> values) {
            addCriterion("player_oid in", values, "playerOid");
            return (Criteria) this;
        }

        public Criteria andPlayerOidNotIn(List<Integer> values) {
            addCriterion("player_oid not in", values, "playerOid");
            return (Criteria) this;
        }

        public Criteria andPlayerOidBetween(Integer value1, Integer value2) {
            addCriterion("player_oid between", value1, value2, "playerOid");
            return (Criteria) this;
        }

        public Criteria andPlayerOidNotBetween(Integer value1, Integer value2) {
            addCriterion("player_oid not between", value1, value2, "playerOid");
            return (Criteria) this;
        }

        public Criteria andCountIsNull() {
            addCriterion("count is null");
            return (Criteria) this;
        }

        public Criteria andCountIsNotNull() {
            addCriterion("count is not null");
            return (Criteria) this;
        }

        public Criteria andCountEqualTo(Integer value) {
            addCriterion("count =", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountEqualToColumn(SkillCard.Column column) {
            addCriterion(new StringBuilder("count = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCountNotEqualTo(Integer value) {
            addCriterion("count <>", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountNotEqualToColumn(SkillCard.Column column) {
            addCriterion(new StringBuilder("count <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCountGreaterThan(Integer value) {
            addCriterion("count >", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountGreaterThanColumn(SkillCard.Column column) {
            addCriterion(new StringBuilder("count > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("count >=", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountGreaterThanOrEqualToColumn(SkillCard.Column column) {
            addCriterion(new StringBuilder("count >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCountLessThan(Integer value) {
            addCriterion("count <", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountLessThanColumn(SkillCard.Column column) {
            addCriterion(new StringBuilder("count < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCountLessThanOrEqualTo(Integer value) {
            addCriterion("count <=", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountLessThanOrEqualToColumn(SkillCard.Column column) {
            addCriterion(new StringBuilder("count <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCountIn(List<Integer> values) {
            addCriterion("count in", values, "count");
            return (Criteria) this;
        }

        public Criteria andCountNotIn(List<Integer> values) {
            addCriterion("count not in", values, "count");
            return (Criteria) this;
        }

        public Criteria andCountBetween(Integer value1, Integer value2) {
            addCriterion("count between", value1, value2, "count");
            return (Criteria) this;
        }

        public Criteria andCountNotBetween(Integer value1, Integer value2) {
            addCriterion("count not between", value1, value2, "count");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeEqualToColumn(SkillCard.Column column) {
            addCriterion(new StringBuilder("type = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualToColumn(SkillCard.Column column) {
            addCriterion(new StringBuilder("type <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanColumn(SkillCard.Column column) {
            addCriterion(new StringBuilder("type > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualToColumn(SkillCard.Column column) {
            addCriterion(new StringBuilder("type >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanColumn(SkillCard.Column column) {
            addCriterion(new StringBuilder("type < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualToColumn(SkillCard.Column column) {
            addCriterion(new StringBuilder("type <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusEqualToColumn(SkillCard.Column column) {
            addCriterion(new StringBuilder("status = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualToColumn(SkillCard.Column column) {
            addCriterion(new StringBuilder("status <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanColumn(SkillCard.Column column) {
            addCriterion(new StringBuilder("status > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualToColumn(SkillCard.Column column) {
            addCriterion(new StringBuilder("status >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanColumn(SkillCard.Column column) {
            addCriterion(new StringBuilder("status < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualToColumn(SkillCard.Column column) {
            addCriterion(new StringBuilder("status <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualToColumn(SkillCard.Column column) {
            addCriterion(new StringBuilder("remark = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualToColumn(SkillCard.Column column) {
            addCriterion(new StringBuilder("remark <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanColumn(SkillCard.Column column) {
            addCriterion(new StringBuilder("remark > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualToColumn(SkillCard.Column column) {
            addCriterion(new StringBuilder("remark >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanColumn(SkillCard.Column column) {
            addCriterion(new StringBuilder("remark < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualToColumn(SkillCard.Column column) {
            addCriterion(new StringBuilder("remark <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualToColumn(SkillCard.Column column) {
            addCriterion(new StringBuilder("create_time = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualToColumn(SkillCard.Column column) {
            addCriterion(new StringBuilder("create_time <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanColumn(SkillCard.Column column) {
            addCriterion(new StringBuilder("create_time > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualToColumn(SkillCard.Column column) {
            addCriterion(new StringBuilder("create_time >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanColumn(SkillCard.Column column) {
            addCriterion(new StringBuilder("create_time < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualToColumn(SkillCard.Column column) {
            addCriterion(new StringBuilder("create_time <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }
    }

    /**
            * This class was generated by MyBatis Generator.
            * This class corresponds to the database table t_skill_card
            *
            * @mbg.generated do_not_delete_during_merge
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    public static class Criteria extends GeneratedCriteria {
        private SkillCardExample example;

        protected Criteria(SkillCardExample example) {
            super();
            this.example = example;
        }

        public SkillCardExample example() {
            return this.example;
        }

        @Deprecated
        public Criteria andIf(boolean ifAdd, ICriteriaAdd add) {
            if (ifAdd) {
                add.add(this);
            }
            return this;
        }

        public Criteria when(boolean condition, ICriteriaWhen then) {
            if (condition) {
                then.criteria(this);
            }
            return this;
        }

        public Criteria when(boolean condition, ICriteriaWhen then, ICriteriaWhen otherwise) {
            if (condition) {
                then.criteria(this);
            } else {
                otherwise.criteria(this);
            }
            return this;
        }

        @Deprecated
        public interface ICriteriaAdd {
            Criteria add(Criteria add);
        }
    }

    /**
            * This class was generated by MyBatis Generator.
            * This class corresponds to the database table t_skill_card
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    public interface ICriteriaWhen {
        void criteria(Criteria criteria);
    }

    public interface IExampleWhen {
        void example(com.yulink.texas.core.domain.SkillCardExample example);
    }
}