package com.yulink.texas.core.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SkillDictionaryExample {
    protected String orderByClause;

    protected boolean distinct;

    protected List<Criteria> oredCriteria;

    protected Integer offset;

    protected Integer rows;

    public SkillDictionaryExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    public String getOrderByClause() {
        return orderByClause;
    }

    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    public boolean isDistinct() {
        return distinct;
    }

    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    public SkillDictionaryExample orderBy(String orderByClause) {
        this.setOrderByClause(orderByClause);
        return this;
    }

    public SkillDictionaryExample orderBy(String ... orderByClauses) {
        StringBuffer sb = new StringBuffer();
        for (int i = 0; i < orderByClauses.length; i++) {
            sb.append(orderByClauses[i]);
            if (i < orderByClauses.length - 1) {
                sb.append(" , ");
            }
        }
        this.setOrderByClause(sb.toString());
        return this;
    }

    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria(this);
        return criteria;
    }

    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
        rows = null;
        offset = null;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public Integer getOffset() {
        return this.offset;
    }

    public void setRows(Integer rows) {
        this.rows = rows;
    }

    public Integer getRows() {
        return this.rows;
    }

    public SkillDictionaryExample limit(Integer rows) {
        this.rows = rows;
        return this;
    }

    public SkillDictionaryExample limit(Integer offset, Integer rows) {
        this.offset = offset;
        this.rows = rows;
        return this;
    }

    public SkillDictionaryExample page(Integer page, Integer pageSize) {
        this.offset = page * pageSize;
        this.rows = pageSize;
        return this;
    }

    public static Criteria newAndCreateCriteria() {
        SkillDictionaryExample example = new SkillDictionaryExample();
        return example.createCriteria();
    }

    public SkillDictionaryExample when(boolean condition, IExampleWhen then) {
        if (condition) {
            then.example(this);
        }
        return this;
    }

    public SkillDictionaryExample when(boolean condition, IExampleWhen then, IExampleWhen otherwise) {
        if (condition) {
            then.example(this);
        } else {
            otherwise.example(this);
        }
        return this;
    }

    /**
            * This class was generated by MyBatis Generator.
            * This class corresponds to the database table t_skill_dictionary
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdEqualToColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("id = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualToColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("id <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("id > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualToColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("id >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("id < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualToColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("id <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSkillDictionaryNoIsNull() {
            addCriterion("skill_dictionary_no is null");
            return (Criteria) this;
        }

        public Criteria andSkillDictionaryNoIsNotNull() {
            addCriterion("skill_dictionary_no is not null");
            return (Criteria) this;
        }

        public Criteria andSkillDictionaryNoEqualTo(String value) {
            addCriterion("skill_dictionary_no =", value, "skillDictionaryNo");
            return (Criteria) this;
        }

        public Criteria andSkillDictionaryNoEqualToColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("skill_dictionary_no = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSkillDictionaryNoNotEqualTo(String value) {
            addCriterion("skill_dictionary_no <>", value, "skillDictionaryNo");
            return (Criteria) this;
        }

        public Criteria andSkillDictionaryNoNotEqualToColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("skill_dictionary_no <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSkillDictionaryNoGreaterThan(String value) {
            addCriterion("skill_dictionary_no >", value, "skillDictionaryNo");
            return (Criteria) this;
        }

        public Criteria andSkillDictionaryNoGreaterThanColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("skill_dictionary_no > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSkillDictionaryNoGreaterThanOrEqualTo(String value) {
            addCriterion("skill_dictionary_no >=", value, "skillDictionaryNo");
            return (Criteria) this;
        }

        public Criteria andSkillDictionaryNoGreaterThanOrEqualToColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("skill_dictionary_no >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSkillDictionaryNoLessThan(String value) {
            addCriterion("skill_dictionary_no <", value, "skillDictionaryNo");
            return (Criteria) this;
        }

        public Criteria andSkillDictionaryNoLessThanColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("skill_dictionary_no < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSkillDictionaryNoLessThanOrEqualTo(String value) {
            addCriterion("skill_dictionary_no <=", value, "skillDictionaryNo");
            return (Criteria) this;
        }

        public Criteria andSkillDictionaryNoLessThanOrEqualToColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("skill_dictionary_no <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSkillDictionaryNoLike(String value) {
            addCriterion("skill_dictionary_no like", value, "skillDictionaryNo");
            return (Criteria) this;
        }

        public Criteria andSkillDictionaryNoNotLike(String value) {
            addCriterion("skill_dictionary_no not like", value, "skillDictionaryNo");
            return (Criteria) this;
        }

        public Criteria andSkillDictionaryNoIn(List<String> values) {
            addCriterion("skill_dictionary_no in", values, "skillDictionaryNo");
            return (Criteria) this;
        }

        public Criteria andSkillDictionaryNoNotIn(List<String> values) {
            addCriterion("skill_dictionary_no not in", values, "skillDictionaryNo");
            return (Criteria) this;
        }

        public Criteria andSkillDictionaryNoBetween(String value1, String value2) {
            addCriterion("skill_dictionary_no between", value1, value2, "skillDictionaryNo");
            return (Criteria) this;
        }

        public Criteria andSkillDictionaryNoNotBetween(String value1, String value2) {
            addCriterion("skill_dictionary_no not between", value1, value2, "skillDictionaryNo");
            return (Criteria) this;
        }

        public Criteria andSkillNameZhIsNull() {
            addCriterion("skill_name_zh is null");
            return (Criteria) this;
        }

        public Criteria andSkillNameZhIsNotNull() {
            addCriterion("skill_name_zh is not null");
            return (Criteria) this;
        }

        public Criteria andSkillNameZhEqualTo(String value) {
            addCriterion("skill_name_zh =", value, "skillNameZh");
            return (Criteria) this;
        }

        public Criteria andSkillNameZhEqualToColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("skill_name_zh = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSkillNameZhNotEqualTo(String value) {
            addCriterion("skill_name_zh <>", value, "skillNameZh");
            return (Criteria) this;
        }

        public Criteria andSkillNameZhNotEqualToColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("skill_name_zh <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSkillNameZhGreaterThan(String value) {
            addCriterion("skill_name_zh >", value, "skillNameZh");
            return (Criteria) this;
        }

        public Criteria andSkillNameZhGreaterThanColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("skill_name_zh > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSkillNameZhGreaterThanOrEqualTo(String value) {
            addCriterion("skill_name_zh >=", value, "skillNameZh");
            return (Criteria) this;
        }

        public Criteria andSkillNameZhGreaterThanOrEqualToColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("skill_name_zh >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSkillNameZhLessThan(String value) {
            addCriterion("skill_name_zh <", value, "skillNameZh");
            return (Criteria) this;
        }

        public Criteria andSkillNameZhLessThanColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("skill_name_zh < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSkillNameZhLessThanOrEqualTo(String value) {
            addCriterion("skill_name_zh <=", value, "skillNameZh");
            return (Criteria) this;
        }

        public Criteria andSkillNameZhLessThanOrEqualToColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("skill_name_zh <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSkillNameZhLike(String value) {
            addCriterion("skill_name_zh like", value, "skillNameZh");
            return (Criteria) this;
        }

        public Criteria andSkillNameZhNotLike(String value) {
            addCriterion("skill_name_zh not like", value, "skillNameZh");
            return (Criteria) this;
        }

        public Criteria andSkillNameZhIn(List<String> values) {
            addCriterion("skill_name_zh in", values, "skillNameZh");
            return (Criteria) this;
        }

        public Criteria andSkillNameZhNotIn(List<String> values) {
            addCriterion("skill_name_zh not in", values, "skillNameZh");
            return (Criteria) this;
        }

        public Criteria andSkillNameZhBetween(String value1, String value2) {
            addCriterion("skill_name_zh between", value1, value2, "skillNameZh");
            return (Criteria) this;
        }

        public Criteria andSkillNameZhNotBetween(String value1, String value2) {
            addCriterion("skill_name_zh not between", value1, value2, "skillNameZh");
            return (Criteria) this;
        }

        public Criteria andSkillNameEnIsNull() {
            addCriterion("skill_name_en is null");
            return (Criteria) this;
        }

        public Criteria andSkillNameEnIsNotNull() {
            addCriterion("skill_name_en is not null");
            return (Criteria) this;
        }

        public Criteria andSkillNameEnEqualTo(String value) {
            addCriterion("skill_name_en =", value, "skillNameEn");
            return (Criteria) this;
        }

        public Criteria andSkillNameEnEqualToColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("skill_name_en = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSkillNameEnNotEqualTo(String value) {
            addCriterion("skill_name_en <>", value, "skillNameEn");
            return (Criteria) this;
        }

        public Criteria andSkillNameEnNotEqualToColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("skill_name_en <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSkillNameEnGreaterThan(String value) {
            addCriterion("skill_name_en >", value, "skillNameEn");
            return (Criteria) this;
        }

        public Criteria andSkillNameEnGreaterThanColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("skill_name_en > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSkillNameEnGreaterThanOrEqualTo(String value) {
            addCriterion("skill_name_en >=", value, "skillNameEn");
            return (Criteria) this;
        }

        public Criteria andSkillNameEnGreaterThanOrEqualToColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("skill_name_en >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSkillNameEnLessThan(String value) {
            addCriterion("skill_name_en <", value, "skillNameEn");
            return (Criteria) this;
        }

        public Criteria andSkillNameEnLessThanColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("skill_name_en < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSkillNameEnLessThanOrEqualTo(String value) {
            addCriterion("skill_name_en <=", value, "skillNameEn");
            return (Criteria) this;
        }

        public Criteria andSkillNameEnLessThanOrEqualToColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("skill_name_en <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSkillNameEnLike(String value) {
            addCriterion("skill_name_en like", value, "skillNameEn");
            return (Criteria) this;
        }

        public Criteria andSkillNameEnNotLike(String value) {
            addCriterion("skill_name_en not like", value, "skillNameEn");
            return (Criteria) this;
        }

        public Criteria andSkillNameEnIn(List<String> values) {
            addCriterion("skill_name_en in", values, "skillNameEn");
            return (Criteria) this;
        }

        public Criteria andSkillNameEnNotIn(List<String> values) {
            addCriterion("skill_name_en not in", values, "skillNameEn");
            return (Criteria) this;
        }

        public Criteria andSkillNameEnBetween(String value1, String value2) {
            addCriterion("skill_name_en between", value1, value2, "skillNameEn");
            return (Criteria) this;
        }

        public Criteria andSkillNameEnNotBetween(String value1, String value2) {
            addCriterion("skill_name_en not between", value1, value2, "skillNameEn");
            return (Criteria) this;
        }

        public Criteria andPowerIsNull() {
            addCriterion("power is null");
            return (Criteria) this;
        }

        public Criteria andPowerIsNotNull() {
            addCriterion("power is not null");
            return (Criteria) this;
        }

        public Criteria andPowerEqualTo(Integer value) {
            addCriterion("power =", value, "power");
            return (Criteria) this;
        }

        public Criteria andPowerEqualToColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("power = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andPowerNotEqualTo(Integer value) {
            addCriterion("power <>", value, "power");
            return (Criteria) this;
        }

        public Criteria andPowerNotEqualToColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("power <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andPowerGreaterThan(Integer value) {
            addCriterion("power >", value, "power");
            return (Criteria) this;
        }

        public Criteria andPowerGreaterThanColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("power > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andPowerGreaterThanOrEqualTo(Integer value) {
            addCriterion("power >=", value, "power");
            return (Criteria) this;
        }

        public Criteria andPowerGreaterThanOrEqualToColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("power >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andPowerLessThan(Integer value) {
            addCriterion("power <", value, "power");
            return (Criteria) this;
        }

        public Criteria andPowerLessThanColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("power < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andPowerLessThanOrEqualTo(Integer value) {
            addCriterion("power <=", value, "power");
            return (Criteria) this;
        }

        public Criteria andPowerLessThanOrEqualToColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("power <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andPowerIn(List<Integer> values) {
            addCriterion("power in", values, "power");
            return (Criteria) this;
        }

        public Criteria andPowerNotIn(List<Integer> values) {
            addCriterion("power not in", values, "power");
            return (Criteria) this;
        }

        public Criteria andPowerBetween(Integer value1, Integer value2) {
            addCriterion("power between", value1, value2, "power");
            return (Criteria) this;
        }

        public Criteria andPowerNotBetween(Integer value1, Integer value2) {
            addCriterion("power not between", value1, value2, "power");
            return (Criteria) this;
        }

        public Criteria andImageIsNull() {
            addCriterion("image is null");
            return (Criteria) this;
        }

        public Criteria andImageIsNotNull() {
            addCriterion("image is not null");
            return (Criteria) this;
        }

        public Criteria andImageEqualTo(String value) {
            addCriterion("image =", value, "image");
            return (Criteria) this;
        }

        public Criteria andImageEqualToColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("image = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andImageNotEqualTo(String value) {
            addCriterion("image <>", value, "image");
            return (Criteria) this;
        }

        public Criteria andImageNotEqualToColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("image <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andImageGreaterThan(String value) {
            addCriterion("image >", value, "image");
            return (Criteria) this;
        }

        public Criteria andImageGreaterThanColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("image > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andImageGreaterThanOrEqualTo(String value) {
            addCriterion("image >=", value, "image");
            return (Criteria) this;
        }

        public Criteria andImageGreaterThanOrEqualToColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("image >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andImageLessThan(String value) {
            addCriterion("image <", value, "image");
            return (Criteria) this;
        }

        public Criteria andImageLessThanColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("image < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andImageLessThanOrEqualTo(String value) {
            addCriterion("image <=", value, "image");
            return (Criteria) this;
        }

        public Criteria andImageLessThanOrEqualToColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("image <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andImageLike(String value) {
            addCriterion("image like", value, "image");
            return (Criteria) this;
        }

        public Criteria andImageNotLike(String value) {
            addCriterion("image not like", value, "image");
            return (Criteria) this;
        }

        public Criteria andImageIn(List<String> values) {
            addCriterion("image in", values, "image");
            return (Criteria) this;
        }

        public Criteria andImageNotIn(List<String> values) {
            addCriterion("image not in", values, "image");
            return (Criteria) this;
        }

        public Criteria andImageBetween(String value1, String value2) {
            addCriterion("image between", value1, value2, "image");
            return (Criteria) this;
        }

        public Criteria andImageNotBetween(String value1, String value2) {
            addCriterion("image not between", value1, value2, "image");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeEqualToColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("type = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualToColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("type <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("type > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualToColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("type >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("type < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualToColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("type <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andPointToIsNull() {
            addCriterion("point_to is null");
            return (Criteria) this;
        }

        public Criteria andPointToIsNotNull() {
            addCriterion("point_to is not null");
            return (Criteria) this;
        }

        public Criteria andPointToEqualTo(String value) {
            addCriterion("point_to =", value, "pointTo");
            return (Criteria) this;
        }

        public Criteria andPointToEqualToColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("point_to = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andPointToNotEqualTo(String value) {
            addCriterion("point_to <>", value, "pointTo");
            return (Criteria) this;
        }

        public Criteria andPointToNotEqualToColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("point_to <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andPointToGreaterThan(String value) {
            addCriterion("point_to >", value, "pointTo");
            return (Criteria) this;
        }

        public Criteria andPointToGreaterThanColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("point_to > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andPointToGreaterThanOrEqualTo(String value) {
            addCriterion("point_to >=", value, "pointTo");
            return (Criteria) this;
        }

        public Criteria andPointToGreaterThanOrEqualToColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("point_to >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andPointToLessThan(String value) {
            addCriterion("point_to <", value, "pointTo");
            return (Criteria) this;
        }

        public Criteria andPointToLessThanColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("point_to < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andPointToLessThanOrEqualTo(String value) {
            addCriterion("point_to <=", value, "pointTo");
            return (Criteria) this;
        }

        public Criteria andPointToLessThanOrEqualToColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("point_to <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andPointToLike(String value) {
            addCriterion("point_to like", value, "pointTo");
            return (Criteria) this;
        }

        public Criteria andPointToNotLike(String value) {
            addCriterion("point_to not like", value, "pointTo");
            return (Criteria) this;
        }

        public Criteria andPointToIn(List<String> values) {
            addCriterion("point_to in", values, "pointTo");
            return (Criteria) this;
        }

        public Criteria andPointToNotIn(List<String> values) {
            addCriterion("point_to not in", values, "pointTo");
            return (Criteria) this;
        }

        public Criteria andPointToBetween(String value1, String value2) {
            addCriterion("point_to between", value1, value2, "pointTo");
            return (Criteria) this;
        }

        public Criteria andPointToNotBetween(String value1, String value2) {
            addCriterion("point_to not between", value1, value2, "pointTo");
            return (Criteria) this;
        }

        public Criteria andLevelIsNull() {
            addCriterion("level is null");
            return (Criteria) this;
        }

        public Criteria andLevelIsNotNull() {
            addCriterion("level is not null");
            return (Criteria) this;
        }

        public Criteria andLevelEqualTo(String value) {
            addCriterion("level =", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelEqualToColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("level = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLevelNotEqualTo(String value) {
            addCriterion("level <>", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotEqualToColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("level <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThan(String value) {
            addCriterion("level >", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThanColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("level > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThanOrEqualTo(String value) {
            addCriterion("level >=", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThanOrEqualToColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("level >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLevelLessThan(String value) {
            addCriterion("level <", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLessThanColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("level < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLevelLessThanOrEqualTo(String value) {
            addCriterion("level <=", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLessThanOrEqualToColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("level <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLevelLike(String value) {
            addCriterion("level like", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotLike(String value) {
            addCriterion("level not like", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelIn(List<String> values) {
            addCriterion("level in", values, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotIn(List<String> values) {
            addCriterion("level not in", values, "level");
            return (Criteria) this;
        }

        public Criteria andLevelBetween(String value1, String value2) {
            addCriterion("level between", value1, value2, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotBetween(String value1, String value2) {
            addCriterion("level not between", value1, value2, "level");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusEqualToColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("status = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualToColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("status <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("status > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualToColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("status >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("status < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualToColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("status <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andUseRoundIsNull() {
            addCriterion("use_round is null");
            return (Criteria) this;
        }

        public Criteria andUseRoundIsNotNull() {
            addCriterion("use_round is not null");
            return (Criteria) this;
        }

        public Criteria andUseRoundEqualTo(String value) {
            addCriterion("use_round =", value, "useRound");
            return (Criteria) this;
        }

        public Criteria andUseRoundEqualToColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("use_round = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUseRoundNotEqualTo(String value) {
            addCriterion("use_round <>", value, "useRound");
            return (Criteria) this;
        }

        public Criteria andUseRoundNotEqualToColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("use_round <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUseRoundGreaterThan(String value) {
            addCriterion("use_round >", value, "useRound");
            return (Criteria) this;
        }

        public Criteria andUseRoundGreaterThanColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("use_round > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUseRoundGreaterThanOrEqualTo(String value) {
            addCriterion("use_round >=", value, "useRound");
            return (Criteria) this;
        }

        public Criteria andUseRoundGreaterThanOrEqualToColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("use_round >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUseRoundLessThan(String value) {
            addCriterion("use_round <", value, "useRound");
            return (Criteria) this;
        }

        public Criteria andUseRoundLessThanColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("use_round < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUseRoundLessThanOrEqualTo(String value) {
            addCriterion("use_round <=", value, "useRound");
            return (Criteria) this;
        }

        public Criteria andUseRoundLessThanOrEqualToColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("use_round <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUseRoundLike(String value) {
            addCriterion("use_round like", value, "useRound");
            return (Criteria) this;
        }

        public Criteria andUseRoundNotLike(String value) {
            addCriterion("use_round not like", value, "useRound");
            return (Criteria) this;
        }

        public Criteria andUseRoundIn(List<String> values) {
            addCriterion("use_round in", values, "useRound");
            return (Criteria) this;
        }

        public Criteria andUseRoundNotIn(List<String> values) {
            addCriterion("use_round not in", values, "useRound");
            return (Criteria) this;
        }

        public Criteria andUseRoundBetween(String value1, String value2) {
            addCriterion("use_round between", value1, value2, "useRound");
            return (Criteria) this;
        }

        public Criteria andUseRoundNotBetween(String value1, String value2) {
            addCriterion("use_round not between", value1, value2, "useRound");
            return (Criteria) this;
        }

        public Criteria andTrapActionIsNull() {
            addCriterion("trap_action is null");
            return (Criteria) this;
        }

        public Criteria andTrapActionIsNotNull() {
            addCriterion("trap_action is not null");
            return (Criteria) this;
        }

        public Criteria andTrapActionEqualTo(String value) {
            addCriterion("trap_action =", value, "trapAction");
            return (Criteria) this;
        }

        public Criteria andTrapActionEqualToColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("trap_action = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTrapActionNotEqualTo(String value) {
            addCriterion("trap_action <>", value, "trapAction");
            return (Criteria) this;
        }

        public Criteria andTrapActionNotEqualToColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("trap_action <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTrapActionGreaterThan(String value) {
            addCriterion("trap_action >", value, "trapAction");
            return (Criteria) this;
        }

        public Criteria andTrapActionGreaterThanColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("trap_action > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTrapActionGreaterThanOrEqualTo(String value) {
            addCriterion("trap_action >=", value, "trapAction");
            return (Criteria) this;
        }

        public Criteria andTrapActionGreaterThanOrEqualToColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("trap_action >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTrapActionLessThan(String value) {
            addCriterion("trap_action <", value, "trapAction");
            return (Criteria) this;
        }

        public Criteria andTrapActionLessThanColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("trap_action < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTrapActionLessThanOrEqualTo(String value) {
            addCriterion("trap_action <=", value, "trapAction");
            return (Criteria) this;
        }

        public Criteria andTrapActionLessThanOrEqualToColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("trap_action <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTrapActionLike(String value) {
            addCriterion("trap_action like", value, "trapAction");
            return (Criteria) this;
        }

        public Criteria andTrapActionNotLike(String value) {
            addCriterion("trap_action not like", value, "trapAction");
            return (Criteria) this;
        }

        public Criteria andTrapActionIn(List<String> values) {
            addCriterion("trap_action in", values, "trapAction");
            return (Criteria) this;
        }

        public Criteria andTrapActionNotIn(List<String> values) {
            addCriterion("trap_action not in", values, "trapAction");
            return (Criteria) this;
        }

        public Criteria andTrapActionBetween(String value1, String value2) {
            addCriterion("trap_action between", value1, value2, "trapAction");
            return (Criteria) this;
        }

        public Criteria andTrapActionNotBetween(String value1, String value2) {
            addCriterion("trap_action not between", value1, value2, "trapAction");
            return (Criteria) this;
        }

        public Criteria andPriorityIsNull() {
            addCriterion("priority is null");
            return (Criteria) this;
        }

        public Criteria andPriorityIsNotNull() {
            addCriterion("priority is not null");
            return (Criteria) this;
        }

        public Criteria andPriorityEqualTo(Integer value) {
            addCriterion("priority =", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityEqualToColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("priority = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andPriorityNotEqualTo(Integer value) {
            addCriterion("priority <>", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityNotEqualToColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("priority <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andPriorityGreaterThan(Integer value) {
            addCriterion("priority >", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityGreaterThanColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("priority > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andPriorityGreaterThanOrEqualTo(Integer value) {
            addCriterion("priority >=", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityGreaterThanOrEqualToColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("priority >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andPriorityLessThan(Integer value) {
            addCriterion("priority <", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityLessThanColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("priority < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andPriorityLessThanOrEqualTo(Integer value) {
            addCriterion("priority <=", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityLessThanOrEqualToColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("priority <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andPriorityIn(List<Integer> values) {
            addCriterion("priority in", values, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityNotIn(List<Integer> values) {
            addCriterion("priority not in", values, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityBetween(Integer value1, Integer value2) {
            addCriterion("priority between", value1, value2, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityNotBetween(Integer value1, Integer value2) {
            addCriterion("priority not between", value1, value2, "priority");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualToColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("description = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualToColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("description <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("description > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualToColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("description >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("description < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualToColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("description <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andConstrainsIsNull() {
            addCriterion("constrains is null");
            return (Criteria) this;
        }

        public Criteria andConstrainsIsNotNull() {
            addCriterion("constrains is not null");
            return (Criteria) this;
        }

        public Criteria andConstrainsEqualTo(String value) {
            addCriterion("constrains =", value, "constrains");
            return (Criteria) this;
        }

        public Criteria andConstrainsEqualToColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("constrains = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andConstrainsNotEqualTo(String value) {
            addCriterion("constrains <>", value, "constrains");
            return (Criteria) this;
        }

        public Criteria andConstrainsNotEqualToColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("constrains <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andConstrainsGreaterThan(String value) {
            addCriterion("constrains >", value, "constrains");
            return (Criteria) this;
        }

        public Criteria andConstrainsGreaterThanColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("constrains > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andConstrainsGreaterThanOrEqualTo(String value) {
            addCriterion("constrains >=", value, "constrains");
            return (Criteria) this;
        }

        public Criteria andConstrainsGreaterThanOrEqualToColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("constrains >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andConstrainsLessThan(String value) {
            addCriterion("constrains <", value, "constrains");
            return (Criteria) this;
        }

        public Criteria andConstrainsLessThanColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("constrains < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andConstrainsLessThanOrEqualTo(String value) {
            addCriterion("constrains <=", value, "constrains");
            return (Criteria) this;
        }

        public Criteria andConstrainsLessThanOrEqualToColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("constrains <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andConstrainsLike(String value) {
            addCriterion("constrains like", value, "constrains");
            return (Criteria) this;
        }

        public Criteria andConstrainsNotLike(String value) {
            addCriterion("constrains not like", value, "constrains");
            return (Criteria) this;
        }

        public Criteria andConstrainsIn(List<String> values) {
            addCriterion("constrains in", values, "constrains");
            return (Criteria) this;
        }

        public Criteria andConstrainsNotIn(List<String> values) {
            addCriterion("constrains not in", values, "constrains");
            return (Criteria) this;
        }

        public Criteria andConstrainsBetween(String value1, String value2) {
            addCriterion("constrains between", value1, value2, "constrains");
            return (Criteria) this;
        }

        public Criteria andConstrainsNotBetween(String value1, String value2) {
            addCriterion("constrains not between", value1, value2, "constrains");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualToColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("remark = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualToColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("remark <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("remark > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualToColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("remark >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("remark < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualToColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("remark <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualToColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("create_time = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualToColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("create_time <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("create_time > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualToColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("create_time >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("create_time < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualToColumn(SkillDictionary.Column column) {
            addCriterion(new StringBuilder("create_time <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }
    }

    /**
            * This class was generated by MyBatis Generator.
            * This class corresponds to the database table t_skill_dictionary
            *
            * @mbg.generated do_not_delete_during_merge
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    public static class Criteria extends GeneratedCriteria {
        private SkillDictionaryExample example;

        protected Criteria(SkillDictionaryExample example) {
            super();
            this.example = example;
        }

        public SkillDictionaryExample example() {
            return this.example;
        }

        @Deprecated
        public Criteria andIf(boolean ifAdd, ICriteriaAdd add) {
            if (ifAdd) {
                add.add(this);
            }
            return this;
        }

        public Criteria when(boolean condition, ICriteriaWhen then) {
            if (condition) {
                then.criteria(this);
            }
            return this;
        }

        public Criteria when(boolean condition, ICriteriaWhen then, ICriteriaWhen otherwise) {
            if (condition) {
                then.criteria(this);
            } else {
                otherwise.criteria(this);
            }
            return this;
        }

        @Deprecated
        public interface ICriteriaAdd {
            Criteria add(Criteria add);
        }
    }

    /**
            * This class was generated by MyBatis Generator.
            * This class corresponds to the database table t_skill_dictionary
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    public interface ICriteriaWhen {
        void criteria(Criteria criteria);
    }

    public interface IExampleWhen {
        void example(com.yulink.texas.core.domain.SkillDictionaryExample example);
    }
}